# title of website
title: index

# description of website
description: jessicayang24's navigation site

# favicon of website
favicon: "https://github.com/jessicayang24.png?size=40"

# your website url
url: https://jessicayang24.github.io/index/

# github profile url
github: "https://github.com/jessicayang24"

# footer message
footer: © 2021-2022 @jessicayang24

# template(theme) of your site, available:
# 1. webstack (http://webstack.cc)
template: webstack

# Google analytics
google_analytics: "G-EXE1PJ8CR2"

webstack:
  search:
    enabled: true
    default: google
    # 可选的搜索引擎
    engines:
      - google
      - github
      - weibo
      - baidu
      - bilibili
      - zhihu

content:
  categories:
    - name: 常用推荐
      sites:
        - name: V2EX
          description: 技术分享平台
          url: https://www.v2ex.com
        - name: GitHub
          description: 代码交流平台
          url: https://github.com/
        - name: AMZ123
          description: 网址导航
          url: https://www.amz123.com
        - name: GitHub加速器
          description: 下载用
          url: https://ghproxy.com/
        - name: SQLBolt
          description: mysql 练习网站
          url: https://sqlbolt.com/
        - name: 阿里天池
          description: 阿里数据集
          url: https://tianchi.aliyun.com/
        - name: Youtube
          description: 全球最大的学习分享平台
          url: https://www.youtube.com/
        - name: UN Comtrade Database
          description: 海关数据查询
          url: https://comtrade.un.org/
        - name: 阿虚的储物间
          description: 导航网址
          url: https://axutongxue.com/
        - name: 新榜
          description: 新媒体数据来源
          url: https://www.newrank.cn
    - name: 新闻门户
      sites:
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
        - name: 
          description: 
          url: 
        - name: Fair Observer
          description: India news
          url: https://www.fairobserver.com/
    - name: 数据工具
      sites:
        - name: 跨境电商网
          description: 跨境电商报告
          url: http://www.100ec.cn/zt/wmds/
        - name: 研报课
          description: 数据分析模型
          url: https://www.yanbaoke.com/
        - name: 极光大数据
          description: 行业数据
          url: https://www.moonfox.cn/
        - name: 贝恩查询
          description: 行业
          url: https://www.bain.cn/
        - name: 发现报告
          description: 行业数据报告查询
          url: https://www.fxbaogao.com/
        - name: AppExchange
          description: 类似天眼查
          url: https://appexchange.salesforce.com/  
        - name: 中财网
          description: 数据引擎
          url: http://data.cfi.cn 
        - name: A/B testing page
          description: Evan’s Awesome A/B Tools
          url: https://www.evanmiller.org/ab-testing/
        - name: Factset
          description: 金融数据和软件公司
          url: https://www.factset.com/
        - name: Kuangstuday
          description: 编程学习平台
          url: https://sqlbolt.com/   
        - name: SQLBolt
          description: mysql 练习网站
          url: https://www.kuangstudy.com 
        - name: YAMM
          description: Gmailyet-another-mail-merge
          url: https://support.yet-another-mail-merge.com/
    - name: 社区资讯
      sites:
        - name: TechCrunch
          description: 美国科技类博客-主要报道新兴互联网公司、评论互联网新产品、发布重大突发新闻
          url: https://techcrunch.com/
        - name: 雷锋网
          description: 人工智能和智能硬件领域的互联网科技媒体
          url: https://www.leiphone.com/
        - name: 电鸭社区
          description: 国内最早的远程工作社区，也是互联网工作者们的聚集地，非常适合设计开发小伙伴关注
          url: https://eleduck.com/
        - name: 廖雪峰的官方网站
          description: 一个教编程的网站
          url: https://www.liaoxuefeng.com/
        - name: GA小站
          description: Google Analytics 分享平台
          url: https://www.ichdata.com/
        - name: 中文马克思注意文库
          description: 深度阅读与学习平台
          url: https://www.marxists.org/chinese/index.html
        - name: 展会网
          description: 国际展会信息公共服务平台
          url: https://www.qufair.com/
    - name: 搜索导航
      sites:
        - name: 5iu
          description: 设计导航
          url: https://hao.5iux.cn
        - name: duckdyckgo
          description: 无痕浏览器
          url: https://www.duckduckgoog.com
        - name: afternic
          description: 域名交易市场
          url: https://www.afternic.com/
    - name: 联盟论坛
      sites:
        - name: warriorforum
          description: 国外论坛 联盟 CPC CPL
          url: https://www.warriorforum.com/
        - name: affiliate-talk
          description: 国外论坛 联盟 
          url: https://www.affiliate-talk.com/
        - name: 云瑞
          description: 优秀设计资源的分享网站
          url: https://www.yrucd.com/
        - name: 稀土区
          description: 优质设计开发资源分享
          url: https://xituqu.com/
        - name: 吾爱破解
          description: 破解资源分享
          url: https://www.52pojie.cn
        - name: 站长
          description: 网站分析
          url: https://ping.chinaz.com
    - name: 在线工具
      sites:
        - name: photopea
          description: 在线作图工具，PS
          url: https://www.photopea.com/
        - name: svgomg
          description: SVG在线压缩平台
          url: https://jakearchibald.github.io/svgomg/
        - name: 稿定抠图
          description: 免费在线抠图软件,图片快速换背景-抠白底图
          url: https://www.gaoding.com
    - name: 开发端
      sites:
        - name: Regex
          description: 爬虫自动加正则以及自动化的工具
          url: https://regex101.com
        - name: Codepen
          description: The best place to build, test, and discover front-end code
          url: https://codepen.io
