# title of website
title: index

# description of website
description: jessicayang24's navigation site

# favicon of website
favicon: "https://github.com/jessicayang24.png?size=40"

# your website url
url: https://jessicayang24.github.io/index/

# github profile url
github: "https://github.com/jessicayang24"

# footer message
footer: © 2021-2021 @jessicayang24

# template(theme) of your site, available:
# 1. webstack (http://webstack.cc)
template: webstack

# Google analytics
google_analytics: "G-EXE1PJ8CR2"

webstack:
  search:
    enabled: true
    default: google
    # 可选的搜索引擎
    engines:
      - google
      - github
      - weibo
      - baidu
      - bilibili
      - zhihu

content:
  categories:
    - name: 常用推荐
      sites:
        - name: V2EX
          description: 技术分享平台
          url: https://www.v2ex.com
        - name: GitHub
          description: 软件设计师交流平台
          url: https://github.com/
        - name: AMZ123
          description: 网址导航
          url: https://www.amz123.com
        - name: GitHub加速器
          description: 下载用
          url: https://ghproxy.com/
        - name: TechCrunch
          description: 美国科技类博客-主要报道新兴互联网公司、评论互联网新产品、发布重大突发新闻
          url: https://techcrunch.com/
        - name: SQLBolt
          description: mysql 练习网站
          url: https://sqlbolt.com/
        - name: Youtube
          description: 全球最大的学习分享平台
          url: https://www.youtube.com/
        - name: UN Comtrade Database
          description: 海关数据查询
          url: https://comtrade.un.org/
        - name: 阿虚的储物间
          description: 导航网址
          url: https://axutongxue.com/
    - name: 数据工具
      sites:
        - name: 研报课
          description: 数据分析模型
          url: https://www.yanbaoke.com/
        - name: 极光大数据
          description: 行业数据
          url: https://www.moonfox.cn/
        - name: 贝恩查询
          description: 行业
          url: https://www.bain.cn/
        - name: 发现报告
          description: 行业数据报告查询
          url: https://www.fxbaogao.com/
        - name: A/B testing page
          description: Evan’s Awesome A/B Tools
          url: https://www.evanmiller.org/ab-testing/
        - name: SQLBolt
          description: mysql 练习网站
          url: https://sqlbolt.com/          
    - name: 社区资讯
      sites:
        - name: 雷锋网
          description: 人工智能和智能硬件领域的互联网科技媒体
          url: https://www.leiphone.com/
        - name: 电鸭社区
          description: 国内最早的远程工作社区，也是互联网工作者们的聚集地，非常适合设计开发小伙伴关注
          url: https://eleduck.com/
        - name: 廖雪峰的官方网站
          description: 一个教编程的网站
          url: https://www.liaoxuefeng.com/
        - name: GA小站
          description: Google Analytics 分享平台
          url: https://www.ichdata.com/
        - name: Reddit
          description: 北美最大社区交流平台
          url: https://www.reddit.com/
        - name: 互联网早读课
          description: 互联网行业深度阅读与学习平台
          url: https://www.zaodula.com/
        - name: 产品壹佰
          description: 为产品经理爱好者提供最优质的产品资讯、原创内容和相关视频课程
          url: http://www.chanpin100.com/
        - name: PMCAFF
          description: 中国第一产品经理人气组织，专注于研究互联网产品
          url: http://www.pmcaff.com/
        - name: 爱运营
          description: 网站运营人员学习交流，专注于网站产品运营管理、淘宝运营。
          url: http://www.iyunying.org/
        - name: 鸟哥笔记
          description: 移动互联网第一干货平台
          url: http://www.niaogebiji.com/
        - name: 古田路9号
          description: 国内专业品牌创意平台
          url: http://www.gtn9.com/
        - name: 优阁网
          description: UI设计师学习交流社区
          url: http://www.uigreat.com/
    - name: 发现产品
      sites:
        - name: NEXT
          description: 不错过任何一个新产品
          url: http://next.36kr.com/posts
        - name: 少数派
          description: 高品质数字消费指南
          url: https://sspai.com/
        - name: 利器
          description: 创造者和他们的工具
          url: http://liqi.io/
        - name: Today
          description: 为身边的新产品喝彩
          url: http://today.itjuzi.com/
        - name: 小众软件
          description: 在这里发现更多有趣的应用
          url: https://faxian.appinn.com/
        - name: afternic
          description: 域名交易市场
          url: https://www.afternic.com/
        - name: UI uigreat
          description: APP界面截图参考
          url: http://ui.uigreat.com/
    - name: LOGO设计
      sites:
        - name: Iconsfeed
          description: iOS icons gallery
          url: http://www.iconsfeed.com/
        - name: iOS Icon Gallery
          description: Showcasing beautiful icon designs from the iOS App Store
          url: http://iosicongallery.com/
        - name: World Vector Logo
          description: Brand logos free to download
          url: https://worldvectorlogo.com/
        - name: Instant Logo Search
          description: Search & download thousands of logos instantly
          url: http://instantlogosearch.com/
    - name: 联盟论坛
      sites:
        - name: warriorforum
          description: 国外论坛 联盟 CPC CPL
          url: https://www.warriorforum.com/
        - name: affiliate-talk
          description: 国外论坛 联盟 
          url: https://www.affiliate-talk.com/
        - name: 云瑞
          description: 优秀设计资源的分享网站
          url: https://www.yrucd.com/
        - name: 稀土区
          description: 优质设计开发资源分享
          url: https://xituqu.com/
        - name: ui8
          description: UI Kits, Wireframe Kits, Templates, Icons and More
          url: https://ui8.net/
        - name: uplabs
          description: Daily resources for product designers & developers
          url: https://www.uplabs.com/
        - name: UIkit.me
          description: 最便捷新鲜的uikit资源下载网站
          url: http://www.uikit.me/
        - name: Fribbble
          description: Free PSD files and other free design resources by Dribbblers.
          url: http://www.fribbble.com/
        - name: PrincipleRepo
          description: Free, High Quality Principle Resources
          url: http://principlerepo.com/
        - name: Designmodo
          description: Web Design Blog and Shop
          url: https://designmodo.com/
    - name: 图形创意
      sites:
        - name: photoshop
          description: Photoshop不需要解释
          url: https://www.adobe.com/cn/products/photoshop.html
        - name: Affinity Designer
          description: 专业创意软件
          url: https://affinity.serif.com/
        - name: Illustrator
          description: 矢量图形和插图。
          url: https://www.adobe.com/cn/products/illustrator/
        - name: indesign
          description: 页面设计、布局和出版。
          url: http://www.adobe.com/cn/products/indesign.html
    - name: 在线工具
      sites:
        - name: tinypng
          description: Optimize your images with a perfect balance in quality and file size.
          url: https://tinypng.com/
        - name: goqr
          description: create QR codes for free (Logo, T-Shirt, vCard, EPS)
          url: http://goqr.me/
        - name: ezgif
          description: simple online GIF maker and toolset for basic animated GIF editing.
          url: https://ezgif.com
        - name: Android 9 patch
          description: Android 9-patch shadow generator fully customizable shadows
          url: http://inloop.github.io/shadow4android/
        - name: screen sizes
          description: Viewport Sizes and Pixel Densities for Popular Devices
          url: http://screensiz.es/
        - name: svgomg
          description: SVG在线压缩平台
          url: https://jakearchibald.github.io/svgomg/
        - name: 稿定抠图
          description: 免费在线抠图软件,图片快速换背景-抠白底图
          url: https://www.gaoding.com
    - name: 视频教程
      sites:
        - name: Photoshop Lady
          description: Your Favourite Photoshop Tutorials in One Place
          url: http://www.photoshoplady.com/
        - name: doyoudo
          description: 创意设计软件学习平台
          url: http://doyoudo.com/
        - name: 没位道
          description: WEB UI免费视频公开课
          url: http://www.c945.com/web-ui-tutorial/
        - name: 慕课网
          description: 程序员的梦工厂（有UI课程）
          url: https://www.imooc.com/
    - name: 设计文章
      sites:
        - name: Web Design Ledger
          description: Web Design Blog
          url: https://webdesignledger.com
