# title of website
title: index

# description of website
description: jessicayang24's navigation site

# favicon of website
favicon: "https://github.com/jessicayang24.png?size=40"

# your website url
url: https://jessicayang24.github.io/index/

# github profile url
github: "https://github.com/jessicayang24"

# footer message
footer: © 2021-2021 @jessicayang24

# template(theme) of your site, available:
# 1. webstack (http://webstack.cc)
template: webstack

# Google analytics
google_analytics: "G-EXE1PJ8CR2"

webstack:
  search:
    enabled: true
    default: google
    # 可选的搜索引擎
    engines:
      - google
      - github
      - weibo
      - baidu
      - bilibili
      - zhihu

content:
  categories:
    - name: 常用推荐
      sites:
        - name: V2EX
          description: 技术分享平台
          url: https://www.v2ex.com
        - name: GitHub
          description: 软件设计师交流平台
          url: https://github.com/
        - name: AMZ123
          description: 网址导航
          url: https://www.amz123.com
        - name: GitHub加速器
          description: 下载用
          url: https://ghproxy.com/
        - name: TechCrunch
          description: 美国科技类博客-主要报道新兴互联网公司、评论互联网新产品、发布重大突发新闻
          url: https://techcrunch.com/
        - name: SQLBolt
          description: mysql 练习网站
          url: https://sqlbolt.com/
        - name: Youtube
          description: 全球最大的学习分享平台
          url: https://www.youtube.com/
        - name: UN Comtrade Database
          description: 海关数据查询
          url: https://comtrade.un.org/
        - name: 阿虚的储物间
          description: 导航网址
          url: https://axutongxue.com/
    - name: 数据工具
      sites:
        - name: 研报课
          description: 数据分析模型
          url: https://www.yanbaoke.com/
        - name: 极光大数据
          description: 行业数据
          url: https://www.moonfox.cn/
        - name: 贝恩查询
          description: 行业
          url: https://www.bain.cn/
        - name: 发现报告
          description: 行业数据报告查询
          url: https://www.fxbaogao.com/
        - name: AppExchange
          description: 类似天眼查
          url: https://appexchange.salesforce.com/          
        - name: A/B testing page
          description: Evan’s Awesome A/B Tools
          url: https://www.evanmiller.org/ab-testing/
        - name: SQLBolt
          description: mysql 练习网站
          url: https://sqlbolt.com/          
    - name: 社区资讯
      sites:
        - name: 雷锋网
          description: 人工智能和智能硬件领域的互联网科技媒体
          url: https://www.leiphone.com/
        - name: 电鸭社区
          description: 国内最早的远程工作社区，也是互联网工作者们的聚集地，非常适合设计开发小伙伴关注
          url: https://eleduck.com/
        - name: 廖雪峰的官方网站
          description: 一个教编程的网站
          url: https://www.liaoxuefeng.com/
        - name: GA小站
          description: Google Analytics 分享平台
          url: https://www.ichdata.com/
        - name: Reddit
          description: 北美最大社区交流平台
          url: https://www.reddit.com/
        - name: 中文马克思注意文库
          description: 深度阅读与学习平台
          url: https://www.marxists.org/chinese/index.html
        - name: 展会网
          description: 国际展会信息公共服务平台
          url: https://www.qufair.com/
    - name: 搜索工具
      sites:
        - name: 5iu
          description: 设计导航
          url: https://hao.5iux.cn
        - name: duckdyckgo
          description: 无痕浏览器
          url: https://www.duckduckgoog.com
        - name: instagram
          description: 社交平台
          url: https://www.instagram.com
        - name: afternic
          description: 域名交易市场
          url: https://www.afternic.com/
    - name: 联盟论坛
      sites:
        - name: warriorforum
          description: 国外论坛 联盟 CPC CPL
          url: https://www.warriorforum.com/
        - name: affiliate-talk
          description: 国外论坛 联盟 
          url: https://www.affiliate-talk.com/
        - name: 云瑞
          description: 优秀设计资源的分享网站
          url: https://www.yrucd.com/
        - name: 稀土区
          description: 优质设计开发资源分享
          url: https://xituqu.com/
    - name: 在线工具
      sites:
        - name: tinypng
          description: Optimize your images with a perfect balance in quality and file size.
          url: https://tinypng.com/
        - name: goqr
          description: create QR codes for free (Logo, T-Shirt, vCard, EPS)
          url: http://goqr.me/
        - name: ezgif
          description: simple online GIF maker and toolset for basic animated GIF editing.
          url: https://ezgif.com
        - name: Android 9 patch
          description: Android 9-patch shadow generator fully customizable shadows
          url: http://inloop.github.io/shadow4android/
        - name: photopea
          description: 在线作图工具，PS
          url: https://www.photopea.com/
        - name: svgomg
          description: SVG在线压缩平台
          url: https://jakearchibald.github.io/svgomg/
        - name: 稿定抠图
          description: 免费在线抠图软件,图片快速换背景-抠白底图
          url: https://www.gaoding.com
    - name: 设计文章
      sites:
        - name: Web Design Ledger
          description: Web Design Blog
          url: https://webdesignledger.com
