# title of website
title: Index

# description of website
description: jessicayang24's navigation site

# favicon of website
favicon: "https://github.com/jessicayang24.png?size=40"

# your website url
url: https://jessicayang24.github.io/index/

# github profile url
github: "https://github.com/jessicayang24"

# footer message
footer: © 2021-2022 @jessicayang24

# template(theme) of your site, available:
# 1. webstack (http://webstack.cc)
template: webstack

# Google analytics
google_analytics: "G-EXE1PJ8CR2"

webstack:
  search:
    enabled: true
    default: google
    # 可选的搜索引擎
    engines:
      - google
      - github
      - weibo
      - baidu
      - bilibili
      - zhihu
